name: sample_app_push_notifications
description: "CometChat Flutter Sample App"
publish_to: 'none'


version: 5.0.0-beta1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  intl: any
  cupertino_icons: ^1.0.2
  cometchat_calls_uikit: ^5.0.0-beta.1
  cometchat_chat_uikit: ^5.0.0-beta.1
  http: ^1.1.0
  toast: ^0.3.0
  path_provider: ^2.1.4
  get: ^4.6.5
  crypto: ^3.0.6
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_apns_x:
    path: ../sample_app_push_notifications/flutter_apns_x
  flutter_apns_only:
    path: ../sample_app_push_notifications/flutter_apns_only
  flutter_callkit_incoming: ^2.0.4+2
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

#dependency_overrides:
#  cometchat_chat_uikit:
#    path: ../chat_uikit
#  cometchat_calls_uikit:
#    path: ../calls_uikit
#  cometchat_uikit_shared:
#    path: ../shared_uikit



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appstore.png"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/
    - assets/sample_app/