// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3FyreEn5kuKehB4c7huXA8lkbWWXxd0c',
    appId: '1:950141434859:android:709cc32dfb5c6494ee77ae',
    messagingSenderId: '950141434859',
    projectId: 'cometchatteammessanger',
    storageBucket: 'cometchatteammessanger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EP9RWuOWJA8PeZ58sd8XvnLbpytuuI8',
    appId: '1:950141434859:ios:cf35b65b26b319c3ee77ae',
    messagingSenderId: '950141434859',
    projectId: 'cometchatteammessanger',
    storageBucket: 'cometchatteammessanger.firebasestorage.app',
    androidClientId: '950141434859-082r7la3902v8l4627r0fq2gfqcek8t2.apps.googleusercontent.com',
    iosClientId: '950141434859-trf8d4lev7b4fn1uavohv87b54ij980g.apps.googleusercontent.com',
    iosBundleId: 'com.cometchat.sampleapp.flutter.ios',
  );
}
